apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  application.properties: |
    server.port=8080
    spring.datasource.url=jdbc:mariadb://${DB_HOST}:3306/student_db
    spring.datasource.username=admin
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true



