apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  application.properties: |
    server.port=8080
    spring.datasource.url=jdbc:mariadb://terraform-20260119102918851700000002.cnmsomggc7sc.us-east-2.rds.amazonaws.com:3306/student_db
    spring.datasource.username=admin
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true



